### PR TITLE
Script for Library Version Update

### PR DESCRIPTION
**Pull request by vojtamolda**
Following the discussion with @sandeepmistry in #58 here's the pull request with bash script that updates the version number wherever it's needed.

### CODE REVIEW

**Comment by sandeepmistry** [comment]
@vojtamolda nice work! Thank you!

I've renamed and made a small optimization in https://github.com/sandeepmistry/arduino-BLEPeripheral/commit/080bb1a6b3504e69e63502edeac7a5984fe53b79. Basically using ```-i ''``` to edit without the need for a backup file as per: https://robots.thoughtbot.com/sed-102-replace-in-place

**Comment by vojtamolda** [comment]
Looks great 👍

**Comment by sandeepmistry** [comment]
@vojtamolda I've tag a new tagged a new version, 0.2.0. Please let me know if things look good on the platform.io side.

**Comment by vojtamolda** [comment]
Hi @sandeepmistry, all looks pretty good there! Downloading and automatic notification about updates both work.

**Comment by sandeepmistry** [comment]
@vojtamolda awesome!

**Pull request merged**
