### PR TITLE
BLESerial Class and Serial Example

### PR DESCRIPTION
**Pull request by vojtamolda**
During one of my projects I run out of pins on my RFDuino and two precious pins normally taken by serial port had to yield to more important purposes. Lack of serial port makes logging and debugging a bit of a challenge...

So, I wrote a subclass of `Stream` and `BLEPeripheral` that implements NUS (Nordic UART Service) - roughly following [this](https://developer.nordicsemi.com/nRF51_SDK/nRF51_SDK_v8.x.x/doc/8.1.0/s110/html/a00078.html). With a little bit of `#define` magic *nRF Toolbox* and *Bluefruit LE* iOS/Android apps can become very handy wireless serial monitors.

I think this may be useful to others as well, so I moved the  `BLESerial` class to the library directory and created a simple `uart.ino` example.

@sandeepmistry, do you think it's worth merging? In a way the functionality is similar to [`examples/RedBearLab/SimpleChat/SimpleChat.ino`](https://github.com/vojtamolda/BLEPeripheral/blob/master/examples/RedBearLab/SimpleChat/SimpleChat.ino) and I'm not 100% sure.

### CODE REVIEW

**Comment by linuxdevel** [comment]
Looks like an excellent abstraction! :)

**Comment by sandeepmistry** [comment]
@vojtamolda nice work!

I've never been a big fan of UART over BLE, but this is a great use case for your pin shortage issue! I'm definitely up for having an example sketch with ```BLESerial``` bundled, but need to think about having ```BLESerial``` in the core API.

@tigoe @don thoughts on this?

**Comment by tigoe** [comment]
I'm not a big fan of UART over BLE either, since it negates the LE, but I can see a use for it. I did a Node example for the Adafruit Feather a couple weeks ago that you can use from the noble side if you like: https://github.com/tigoe/BluetoothLE-Examples/tree/master/noble/readSerial

I think since there is no standard UUID for serial, I'd recommend going with the Nordic number that Adafruit did, it's the one I used in that sketch. That way we start to set a de facto standard, in the absence of one set in the spec.

**Comment by don** [comment]
@sandeepmistry I'd make this an example rather than part of the core APIs

**Comment by vojtamolda** [comment]
It seems like the consensus here is clear, so I moved `BLESerial` class to it's new home in the `examples` folder.

Over the weekend I've added a few improvements that provide better compatibility with `#define Serial BLESerial`

**Comment by tigoe** [comment]
#define Serial BLESerial 

seems like an unwise move, given the centrality of Serial to the core Arduino libraries. I wouldn't ever recommend that to users. Better to do as is done with SoftwareSerial and make a new instance of BLESerial and .begin()  it.

**Comment by vojtamolda** [comment]
@tigoe I didn't mean `#define Serial BLESerial` literally. It's not part of the sketch code or anything. It served only as a goal, that I wanted to achieve - a dirty but quick way to switch my sketch to some form of wireless logging.

**Comment by tigoe** [comment]
Oh, I see. I do similar things on the Yun with Console. I usually just resort to search-and-replace Serial for Console, unless I have a reason to do both.

**Comment by vojtamolda** [comment]
I usually do that too, but magical `#define` looks better in comments, so I can brag about it more 😀

**Comment by sandeepmistry** [comment]
@vojtamolda thanks for moving the file!

It would be good to select one of either serial or UART in the name. Right now the example is in a folder/sketch named ```uart``` and the class name is ```BLESerial```. So, the name the folder could be changed to ```serial``` or change the class to ```BLEUART```. Thoughts?

I'm wondering if we can hide the call to ```BLESerial.poll();``` by making the API's call it internally?
 * ```BLESerial::available```, ```BLESerial::peek```, ```BLESerial::read```, ```BLESerial::write```.

This could mess up the write queue though ...

**Comment by vojtamolda** [comment]
I agree that the sketch and class names are a bit inconsistent, I prefer renaming sketch to `serial.ino`, because `BLEUART` is hard to decrypt.

About the `BLESerial::poll()` calls - I'm not against it, but I'm not sure if I see all the consequences. Here are my thoughts:
 1. Call to `poll()` is quite expensive, right? Maybe I'm wrong and it's just fast jump through a few switches, but judging purely by the number of lines it seems quite big. I wouldn't call `poll()` unconditionally:
   - `peek()` and `read()` -  I'd call it only if RX buffer is empty. If there are some unprocessed data left, I see no benefit of fetching more.
   - `available()` - This method seems like a good place for unconditional `poll()`.
   - `write(...)` - I don't think it's needed here.
   - `flush()` - I drilled a little bit into `BLECharacteristic::setValue(...)` and calling `poll()` immediately after (i.e. - whenever TX buffer is full) makes very good sense. This way new data would be sent immediately instead of waiting in limbo until another `poll()`.

 2. Even with `poll()`-ing APIs I wouldn't remove the call from the example's `loop()` routine. Simply because all the other examples do it too. Similar pattern will indicate to users that they can expect `BLESerial` to behave just as a regular `BLEPeripheral` with a some extra functionality borrowed from `Serial`.

 3. Greatest benefit I see is that no `poll()` in `loop()` call is certainly a step closer to my original goal of `#define Serial BLESerial`

PS: I'm leaving for vacation in a few days. I'm not sure how frequently will my wife let me reply here, so I apologize in advance :-D

**Comment by sandeepmistry** [comment]
> I agree that the sketch and class names are a bit inconsistent, I prefer renaming sketch to serial.ino. BLEUART is hard to decrypt.

That sounds good to me.

> Call to poll() is quite expensive, right? Maybe I'm wrong and it's just fast jump through a few switches, but judging purely by the number of lines it seems quite big.

I wouldn't consider it expensive, it's essential to handle the radio related events, so they don't get dropped. Other Arduino libraries for the nRF8001 mostly use interrupts, so this is not an issue for them.

For ```peek()``` and ```read()``` more writes requests could come in from the central, while the buffer is being processed. I would stick it in ```write```, for sketches that are in a tight write loop, disconnects and unsubscribes could be detected earlier.

> Even with poll()-ing APIs I wouldn't remove the call from the example's loop() routine. Simply because all the other examples do it too. Similar pattern will indicate to users that they can expect BLESerial to behave just as a regular BLEPeripheral with a some extra functionality borrowed from Serial.

Good point! It is also be needed to process the TX queue you've implemented.

> Greatest benefit I see is that no poll() in loop() call is certainly a step closer to my original goal of #define Serial BLESerial

Yes, that's what I was thinking of. Maybe thinking of it more as a network socket is a better approach. BLESerial won't really behave exactly like Serial in the end, mostly because of the reliance on BLEPeripheral poll method. So maybe's it best not to hide this from the user.

Again, I might be over thinking this ...

> PS: I'm leaving for vacation in a few days. I'm not sure how frequently will my wife let me reply here, so I apologize in advance :-D

No worries! Let's continue the discussion when you get back :)

**Comment by monteslu** [comment]
UART over BLE isn't optimal, but it's a super important thing to have.

It's the only way for the foreseeable future to allow web apps to have direct serial communications.  The navigator.bluetooth API will allow us to do things like send firmata commands to an arduino without having to use an internet connection on both ends.

Sure we can use packaged apps for chrome.serial or use electron with node, but BLE serial gives us a generic bridge to hardware from webpages that we didn't have before. 

Seems like it could fit into core.

**Comment by soundanalogous** [comment]
@monteslu you don't need to simulate a UART over BLE to use BLE in the web. It's sort of a crutch for people who are familiar with Serial but haven't put a lot of time into learning how BLE works yet. For something like Firmata it would be much easier to implement since Firmata is Stream-based, but in the longer term I think a general approach of assigning BLE services to core Arduino features (DigitalIO service, AnalogIO service, DeviceInfo service, I2C service, etc) is a better approach for a device control protocol over BLE than Firmata. That said this BLESerial implementation will be useful.

**Comment by monteslu** [comment]
@soundanalogous definitely.  In fact I'm using BLE and noble on the web to control an RGB LED here:  https://github.com/monteslu/coolbeans
Going forward I think GPIO services and characteristics would be awesome.
For cases where power consumption isn't as much of a deterrent or if we just want to relay to something that already requires serial, I'd use this.

**Comment by sandeepmistry** [comment]
@soundanalogous 

> ... but in the longer term I think a general approach of assigning BLE services to core Arduino features (DigitalIO service, AnalogIO service, DeviceInfo service, I2C service, etc) is a better approach for a device control protocol over BLE than Firmata. That said this BLESerial implementation will be useful.

I agree with @monteslu, this would be awesome.

There was an example like this in the 101 core, but it was removed because to was too complex to be a bundled example.

https://github.com/01org/corelibs-arduino101/commit/3c848247e8be8dd1b9c9622ebb4cb09fc2e6379e

> I don't think it belongs in the core either. I can copy the example (once it's merged) and try it with the CurieBLE library (looks like it will be compatible with a couple of minor tweaks) as a BLEStream wrapper for Firmata for the Arduino 101.

Yes, the libraries for the most part are compatible, there are a few API's missing in the CurieBle lib, hoping those can be added in the future.

I'm looking at splitting out the higher level API from the chip specific layer, so the only thing that would differ is the include header and maybe the constructor args for BLEPeripheral (for example, the nRF8001 needs a ready, request, and reset pin - but would have defaults). Right now there is a copy of some of the classes in both repo's, will see if Git submodules or subtrees can be used to share the common code.

**Comment by vojtamolda** [comment]
Hello everyone,
From the discussion here it seems that serial port over BLE is quite controversial topic. After going through all the comments, these are the practical implications I see:

1. Rename the example sketch to `serial\serial.ino`
2. All `Stream` APIs now call `poll()` at some point.`operator bool()` calls it indirectly via `BLEPeripheral::connected()`

**Comment by soundanalogous** [comment]
@vojtamolda I copied your code and am using it here: https://github.com/firmata/arduino/blob/ble/utility/BLEStream.cpp.

I found changing `poll` to a boolean was helpful so it may be useful making that change here as well. Other than than I removed some of the logging that I didn't need for Firmata and also removed args to BLEPeripheral constructor (since they aren't needed for Arduino 101). Working well so far. I haven't looked into your most recent changes yet.

**Comment by soundanalogous** [comment]
Looking over your latest updates. Is it necessary to call `poll` on each Stream method when it's also called on each iteration of the Arduino `loop` function, especially when you are calling it now on each iteration while [the TX buffer is not full](https://github.com/vojtamolda/BLEPeripheral/commit/72d73c50e097b567e2032c5cd71a8b27763b45e5#diff-ba2bcc16bc1312c12c7e713cee4f9202R34).

**Comment by vojtamolda** [comment]
@soundanalogous You're right that calls to `poll()` from every Stream API, aren't absolutely necessary. But I think doing it helps more than it hurts for a lot of possible usage scenarios. My efforts were directed towards having the ability to do `#define Serial BLESerial` without any other code changes.

Here's my explanation why each method does `poll()`:

 - `peek()` and `read()` do `poll()` in case new data would come when the RX buffer is being processed.
 - `available()` does it to return the true number of unprocessed bytes. This way code like `while (BLESerial.available() < 10) { /*wait*/ }` works as it would for Arduino's built-in Serial.
 - `flush()` benefits the most, since the full packet of data that is sent right away.
 - `write()` calls `poll()` to detect disconnects earlier. I feel that this one is the most questionable as it still doesn't guarantee that data written into the TX buffer will be transmitted. On the other hand, after the central device disconnects there's not much one can do with the unprocessed TX buffer.
 - `operator bool()` does it so `while (!BLESerial) { /*wait*/ }` works.

**Comment by sandeepmistry** [comment]
@soundanalogous any more feedback on this or can I go ahead and merge the changes?

**Comment by soundanalogous** [comment]
I have no additional feedback

**Comment by sandeepmistry** [comment]
@vojtamolda thanks for submitting, and your patience!

I've pushed a few other changes:
 * https://github.com/sandeepmistry/arduino-BLEPeripheral/commit/d08a228eb0939b02cccc7d501d179b16ba80a853 to update the example link
 * https://github.com/sandeepmistry/arduino-BLEPeripheral/commit/eaedd3b9279f09f21e8c8db153af7c76096f754b to remove ```BLESerial``` for keywords.txt

**Comment by vojtamolda** [comment]
@sandeepmistry My pleasure. BTW I think, I was the one on vacation, delaying the whole thing :-)

Thanks for the few other changes. I completely missed those.

**Pull request merged**
