### PR TITLE
Add support for RBL nRF52832 boards

### PR DESCRIPTION
**Pull request by sandeepmistry**
As requested in #179.

For the Arduino Core: https://github.com/redbear/nRF5x/tree/master/nRF52832/arduino

### CODE REVIEW

**Comment by sandeepmistry** [comment]
cc/ @don

**Comment by soundanalogous** [comment]
I saw this and was happy, then I check RBL's code only to see they are still breaking everything in favor of MBED: https://github.com/redbear/nRF5x/blob/master/nRF52832/arduino/arduino-1.8.0/hardware/RBL/RBL_nRF52832/cores/RBL_nRF52832/WStream.h#L39. Sigh....

**Comment by drmpf** [comment]
```
#if defined( NRF52 )
  #include <WStream.h>
  #define Stream WStream
#else
  #include <Stream.h>
#endif
```
seems to work

**Comment by soundanalogous** [comment]
Yeah something like that would work (but I'd use a constant that identifies the specific board since NRF52 may actually apply to boards from other vendors at some point), but it gives into the issue rather than putting pressure to fix it (RBL's code is broken, not mine). But yeah, after 2 years back and forth on this issue I must either give in or give up.

**Comment by drmpf** [comment]
I agree,  there is a bug in the RedBear NanoV2 Board code for Arduino.
The  `ARDUINO_RBL_nRF52832`  define is NOT defined when the extra libraries are compiled.
Took me a while to work that one out.

**Comment by drmpf** [comment]
Any idea when V0.5.0 will be published with this merge?
I have published an [instructable](https://www.instructables.com/id/Redbear-Nano-BLE-Custom-Controls-With-PfodApp-No-C/) for BLE Nano V2 based on V0.4.0 with instructions to overwrite the two files.

**Pull request merged**
